-- MySQL Script generated by MySQL Workbench
-- Sáb 06 Mai 2017 11:41:48 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema show_do_milhao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema show_do_milhao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `show_do_milhao` DEFAULT CHARACTER SET utf8 ;
USE `show_do_milhao` ;

-- -----------------------------------------------------
-- Table `show_do_milhao`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `show_do_milhao`.`Professor` (
  `idProfessor` INT NOT NULL,
  `Nome` VARCHAR(200) NOT NULL,
  `CPF` VARCHAR(14) NOT NULL,
  `Email` VARCHAR(150) NOT NULL,
  `Curriculo` VARCHAR(150) NOT NULL,
  `Instituicao` VARCHAR(150) NOT NULL,
  `Titulacao` VARCHAR(150) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProfessor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `show_do_milhao`.`Jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `show_do_milhao`.`Jogo` (
  `idJogo` INT NOT NULL AUTO_INCREMENT,
  `tempo` INT UNSIGNED NOT NULL,
  `disciplina` VARCHAR(100) NOT NULL,
  `curso` VARCHAR(100) NOT NULL,
  `Professor_idProfessor` INT NOT NULL,
  PRIMARY KEY (`idJogo`),
  INDEX `fk_Jogo_Professor1_idx` (`Professor_idProfessor` ASC),
  CONSTRAINT `fk_Jogo_Professor1`
    FOREIGN KEY (`Professor_idProfessor`)
    REFERENCES `show_do_milhao`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `show_do_milhao`.`Jogador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `show_do_milhao`.`Jogador` (
  `idJogador` INT NOT NULL,
  `Nome` VARCHAR(200) NOT NULL,
  `Instituicao` VARCHAR(150) NOT NULL,
  `Equipe` VARCHAR(100) NULL,
  `CPF` VARCHAR(14) NOT NULL,
  `Email` VARCHAR(150) NOT NULL,
  `Senha` VARCHAR(45) NULL,
  PRIMARY KEY (`idJogador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `show_do_milhao`.`Partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `show_do_milhao`.`Partida` (
  `idPartida` INT NOT NULL,
  `Pontuacao` INT UNSIGNED NOT NULL,
  `Data` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `Duracao` INT NULL,
  `Jogo_idJogo` INT NOT NULL,
  `Jogador_idJogador` INT NOT NULL,
  PRIMARY KEY (`idPartida`),
  INDEX `fk_Partida_Jogo_idx` (`Jogo_idJogo` ASC),
  INDEX `fk_Partida_Jogador1_idx` (`Jogador_idJogador` ASC),
  CONSTRAINT `fk_Partida_Jogo`
    FOREIGN KEY (`Jogo_idJogo`)
    REFERENCES `show_do_milhao`.`Jogo` (`idJogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partida_Jogador1`
    FOREIGN KEY (`Jogador_idJogador`)
    REFERENCES `show_do_milhao`.`Jogador` (`idJogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `show_do_milhao`.`Perguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `show_do_milhao`.`Perguntas` (
  `idPerguntas` INT NOT NULL,
  `Enunciado` VARCHAR(200) NOT NULL,
  `Respostas` VARCHAR(200) NOT NULL,
  `Jogo_idJogo` INT NOT NULL,
  PRIMARY KEY (`idPerguntas`),
  INDEX `fk_Perguntas_Jogo1_idx` (`Jogo_idJogo` ASC),
  CONSTRAINT `fk_Perguntas_Jogo1`
    FOREIGN KEY (`Jogo_idJogo`)
    REFERENCES `show_do_milhao`.`Jogo` (`idJogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `show_do_milhao`.`Ajudas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `show_do_milhao`.`Ajudas` (
  `idAjudas` INT NOT NULL,
  `Universitarios` VARCHAR(45) NULL,
  `Cartas` VARCHAR(45) NULL,
  `Pulo` VARCHAR(45) NULL,
  `Perguntas_idPerguntas` INT NOT NULL,
  PRIMARY KEY (`idAjudas`),
  INDEX `fk_Ajudas_Perguntas1_idx` (`Perguntas_idPerguntas` ASC),
  CONSTRAINT `fk_Ajudas_Perguntas1`
    FOREIGN KEY (`Perguntas_idPerguntas`)
    REFERENCES `show_do_milhao`.`Perguntas` (`idPerguntas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `show_do_milhao`.`Alternativas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `show_do_milhao`.`Alternativas` (
  `idAlternativas` INT NOT NULL,
  `Descricao` VARCHAR(200) NOT NULL,
  `Perguntas_idPerguntas` INT NOT NULL,
  PRIMARY KEY (`idAlternativas`),
  INDEX `fk_Alternativas_Perguntas1_idx` (`Perguntas_idPerguntas` ASC),
  CONSTRAINT `fk_Alternativas_Perguntas1`
    FOREIGN KEY (`Perguntas_idPerguntas`)
    REFERENCES `show_do_milhao`.`Perguntas` (`idPerguntas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
